# Generated by Django 5.2.4 on 2025-08-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('SETTLED', 'Settled'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
