# Generated by Django 5.2.4 on 2025-08-02 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('splits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='splits', to='expenses.expense'),
        ),
    ]
