# Generated by Django 5.2.4 on 2025-08-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splits', '0002_alter_split_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='split',
            name='percentage',
        ),
        migrations.AddField(
            model_name='split',
            name='share_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='split',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('unequal', 'Unequal'), ('percentage', 'Percentage')], default='equal', max_length=10),
        ),
        migrations.AlterField(
            model_name='split',
            name='amount_owed',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='split',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
