# Generated by Django 5.2.4 on 2025-08-15 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_idx_expense_group_and_more'),
        ('splits', '0003_remove_split_percentage_split_share_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='split',
            index=models.Index(fields=['expense'], name='idx_split_expense'),
        ),
        migrations.AddIndex(
            model_name='split',
            index=models.Index(fields=['user'], name='idx_split_user'),
        ),
    ]
