# Generated by Django 5.2.4 on 2025-08-13 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_avatar'),
        ('group_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupuser',
            unique_together={('group', 'user')},
        ),
    ]
