# Generated by Django 5.2.4 on 2025-08-15 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('group', '0004_alter_group_avatar_alter_group_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group'], name='idx_expense_group'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by'], name='idx_expense_paid_by'),
        ),
    ]
