# Generated by Django 5.2.4 on 2025-08-06 07:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0003_alter_group_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creditor', models.ForeignKey(help_text='User who is owed the amount.', on_delete=django.db.models.deletion.PROTECT, related_name='debts_due', to=settings.AUTH_USER_MODEL)),
                ('debtor', models.ForeignKey(help_text='User who owes the amount.', on_delete=django.db.models.deletion.PROTECT, related_name='debts_owed', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='group.group')),
            ],
        ),
    ]
