# Generated by Django 5.2.4 on 2025-08-01 08:23

import apps.group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.group.models.avatar_upload_path),
        ),
    ]
