# Generated by Django 5.2.4 on 2025-08-15 04:04

import apps.group.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.group.models.avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), django.core.validators.MaxLengthValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(message='Group name must be between 3 and 120 characters and can only contain letters, numbers, spaces, and hyphens.', regex='^[a-zA-Z0-9\\s-]{3,120}$')]),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_by'], name='idx_group_created_by'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='group_non_empty_name'),
        ),
    ]
