# Generated by Django 5.2.4 on 2025-08-01 08:23

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.user_avatar_upload_path),
        ),
    ]
