# Generated by Django 5.2.4 on 2025-08-06 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_pendinguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='password',
            field=models.CharField(unique=True),
        ),
    ]
