# Generated by Django 5.2.4 on 2025-08-15 04:04

import apps.user.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.user_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif', 'webp']), django.core.validators.MaxLengthValidator(5242880)]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(editable=None, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number validation Error.', regex='^98[4-9]\\d{7}$')]),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='pendinguser',
            name='otp',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='OTP must be 4 digits.', regex='^\\d{4}$')]),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['phone'], name='idx_customuser_phone'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='customuser_non_empty_email'),
        ),
    ]
